Repository FRONTENDSCHOOL10/Trinity, pull requests merged in 2024-07, with the labels that each got.

#19 Fix/header/jinyong
  src/assets/header/TAING_logo.svg
  src/assets/header/close_default.svg
  src/assets/header/close_hover.svg
  src/assets/header/desktop_close_default.png
  src/assets/header/desktop_close_hover.png
  src/assets/header/desktop_live_default.png
  src/assets/header/desktop_live_hover.png
  src/assets/header/desktop_logo.png
  src/assets/header/desktop_paramount_default.png
  src/assets/header/desktop_paramount_hover.png
  src/assets/header/desktop_search_default.png
  src/assets/header/desktop_search_hover.png
  src/assets/header/live_default.svg
  src/assets/header/live_hover.svg
  src/assets/header/mobile_close_default.png
  src/assets/header/mobile_close_hover.png
  src/assets/header/mobile_logo.png
  src/assets/header/mobile_search_default.png
  src/assets/header/mobile_search_hover.png
  src/assets/header/paramount_default.svg
  src/assets/header/paramount_hover.svg
  src/assets/header/search_default.svg
  src/assets/header/search_hover.svg
  src/assets/header/tablet_close_default.png
  src/assets/header/tablet_close_hover.png
  src/assets/header/tablet_live_default.png
  src/assets/header/tablet_live_hover.png
  src/assets/header/tablet_logo.png
  src/assets/header/tablet_paramount_default.png
  src/assets/header/tablet_paramount_hover.png
  src/assets/header/tablet_search_default.png
  src/assets/header/tablet_search_hover.png
  src/components/header/main.js
  src/styles/css/main.css
  src/styles/scss/layout/header.scss
Labels: bug

#25 style: a11yHidden믹스인 추가
  src/styles/scss/utils/_global.scss
Labels: 수정, Done

#27 Feature/event slider/jinyong
  src/assets/event/디저트메이커.png
  src/assets/event/디저트메이커@2x.png
  src/assets/event/디저트메이커@3x.png
  src/assets/event/렛미인.png
  src/assets/event/렛미인@2x.png
  src/assets/event/렛미인@3x.png
  src/assets/event/슈룹.png
  src/assets/event/슈룹@2x.png
  src/assets/event/슈룹@3x.png
  src/assets/event/신비아파트.png
  src/assets/event/신비아파트@2x.png
  src/assets/event/신비아파트@3x.png
  src/assets/event/재벌집막내아들.png
  src/assets/event/재벌집막내아들@2x.png
  src/assets/event/재벌집막내아들@3x.png
  src/assets/event/환승연애.png
  src/assets/event/환승연애@2x.png
  src/assets/event/환승연애@3x.png
  src/components/adBanner/adBanner.scss
  src/components/contentSlider/live/live.html
  src/components/contentSlider/must/must.html
  src/components/contentSlider/only/only.html
  src/components/contentSlider/popular/popular.html
  src/components/contentSlider/quick/quick.html
  src/components/eventSlider/eventSlider.css
  src/components/eventSlider/eventSlider.html
  src/components/eventSlider/eventSlider.js
  src/components/eventSlider/eventSlider.scss
  src/styles/scss/modules/contentSlider.scss
  src/styles/scss/modules/eventSlider.scss
Labels: Done, 기능 구현

#29 fix: 경로 문제 수정
  index.html
  main.js
  vite.config.js
Labels: bug, Done

#33 fix: footer Simple type 추가
  index.html
  src/components/footer/index.html
  src/index.html
  src/main.js
  src/styles/scss/layout/footer.scss
Labels: 수정

#41 feature/landing page/hsw
  pocketbase/pb_data/logs.db
  src/pages/landingPage/landing.html
  src/pages/landingPage/landingpageTVING.html
  src/pages/landingPage/main.js
  src/pages/loginPage/login.html
  src/pages/loginPage/main.js
  src/styles/scss/layout/login.scss
  src/styles/scss/main.scss
Labels: Ongoing, 기능 구현

#47 fix: 비밀번호 아이콘 toggle 수정
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
  src/styles/signUp.scss
Labels: 수정, Done

#54 fix: 메인 비주얼 아이콘 소스 깨짐 현상 해결
  src/components/mainVisual/mainVisual.js
Labels: bug, Done

#57 fix:눈 아이콘 사라지는 현상 수정완료(경로수정)
  src/pages/login/login.js
  src/styles/login.scss
Labels: 수정

#58 modi: login 페이지에 header, footer 추가
  src/pages/login/index.html
  src/pages/login/login.js
  src/styles/login.scss
Labels: 수정, Done, 기능 추가

#66 Feature/profile menu/jinyong
  src/components/profileMenu/profileMenu.html
  src/components/profileMenu/profileMenu.js
  src/styles/modules/profileMenu.scss
Labels: Done, 기능 구현

#67 mode: 메인페이지에 프로필 메뉴 연결
  src/components/profileMenu/profileMenu.js
  src/pages/main/main.js
  src/styles/main.scss
Labels: 수정, Done

#70 Feature/serach modal/jin
  public/icon/search/iconSearchDelete.svg
  public/icon/search/iconSearchDeleteAll.svg
  src/components/searchModal/searchModal.html
  src/components/searchModal/searchModal.js
  src/styles/main.scss
  src/styles/modules/searchModal.scss
Labels: Done

#71 modi: 이전 login.js 함수로 되돌림: 클로져 해제
  src/pages/login/login.js
Labels: bug, 수정

#73 feature: 메인페이지 광고 모달 구현 완료
  src/components/mainAd/mainAd.html
  src/components/mainAd/mainAd.js
  src/styles/modules/mainAd.scss
Labels: Done, 기능 구현

#74 fix:login.js 개편
  src/pages/login/index.html
  src/pages/login/login.js
  src/styles/login.scss
Labels: 수정, Done

#75 fix: user agent stylesheet로 틀어진 폰트 수정
  src/pages/login/index.html
  src/styles/login.scss
Labels: css

#76 modi: 메인페이지 검색 모달, 광고 모달 병합
  src/components/mainAd/mainAd.js
  src/components/profileMenu/profileMenu.js
  src/components/searchModal/searchModal.js
  src/pages/main/main.js
  src/styles/layout/header.scss
  src/styles/main.scss
  src/styles/modules/searchModal.scss
Labels: 수정, Done, 기능 추가, css

#77 fix: 메인페이지에서 로그인 여부 확인 코드 수정
  src/pages/main/main.js
Labels: bug, Done

#78 modi: icon 경로 수정
  src/styles/layout/footer.scss
Labels: 수정

#79 feat: landing페이지 스타일링 수정
  src/styles/landing.scss
Labels: css

#82 fix: 로그인 후 이동할 페이지 경로 설정
  src/pages/login/login.js
Labels: 수정

#80 Feature/profile/narae
  public/icon/profile/iconEditProfile.svg
  public/icon/profile/iconLockedProfile.svg
  public/icon/profile/imgProfile01.png
  public/icon/profile/imgProfile02.png
  public/icon/profile/imgProfile03.png
  public/icon/profile/imgProfile04.png
  src/pages/profileEdit/index.html
  src/pages/profileEdit/profileEdit.js
  src/pages/profileSelect/index.html
  src/pages/profileSelect/profileSelect.js
  src/styles/profile.scss
  vite.config.js
Labels: 기능 구현

#86 페이지 경로 및 아이콘 수정
  src/pages/profileSelect/index.html
  src/pages/profileSelect/profileSelect.js
Labels: bug, 수정

#88 style:button 컴포넌트화
  src/pages/landing/index.html
  src/styles/landing.scss
Labels: 수정, css

#89 feat: 로그인 시 설정한 프로필 동기화 구현
  src/components/profileMenu/profileMenu.js
  src/layout/header/header.js
  src/pages/main/main.js
  src/pages/profileEdit/index.html
  src/styles/layout/header.scss
Labels: 기능 구현

#91 style: 시청 중 콘텐츠 스타일링 완성
  public/icon/main/iconMore.svg
  public/icon/main/iconReplay.svg
  src/components/contentSlider/watching/watching.js
  src/styles/modules/contentSlider/watching.scss
Labels: Done, 기능 구현

#93 Feature/landing/hsw
  src/pages/landing/index.html
  src/pages/landing/landing.js
  src/styles/landing.scss
Labels: 수정, Done, 기능 구현

#99 fix: 회원가입 실패 시 조건 처리 후 알림 문구 발생
  src/pages/signUp/signUp.js
Labels: 수정, Done

#100 Feat/profile edit/hsw
  public/icon/profile/iconPlus.png
  src/pages/profileCreate/index.html
  src/pages/profileCreate/profileCreate.js
  src/pages/profileEdit/profileEdit.js
  src/pages/profileEditing/index.html
  src/pages/profileEditing/profileEditing.js
  src/styles/profile.scss
Labels: 기능 구현, 기능 추가

#101 fix: searchModal 내부로직 변경
  src/components/searchModal/searchModal.js
Labels: bug, 수정, Done, 기능 구현, 기능 추가

#109 Fix/profile select/hsw
  src/pages/profileSelect/profileSelect.js
Labels: 수정

#110 Fix/search modal/hsw
  src/components/searchModal/searchModal.js
Labels: 수정, Done

#112 Feature/search result/jin
  src/pages/searchResult/index.html
  src/pages/searchResult/searchResult.js
  src/styles/main.scss
  src/styles/searchResult.scss
Labels: css

#113 Fix/profile/hsw
  src/pages/profileEdit/profileEdit.js
  src/styles/profileCreateEditing.scss
Labels: bug, 수정, Done

#115 fix: 프로필 모달 키보드 접근성 개선
  src/components/profileMenu/profileMenu.js
Labels: 수정, Done

#116 fix: attribute명 잘못 설정된 것 수정하여 버그 고침
  src/pages/profileEdit/profileEdit.js
Labels: bug, 수정
